name: Metadata refresh

on:
  schedule:
    - cron: 0 3 * * 1-6
  workflow_dispatch:

jobs:
  get-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: sudo apt-get update && sudo apt-get install -y git
      - run: yarn install --frozen-lockfile
      - run: yarn run build:data:metadata
        env:
          GH_API_CONCURRENCY_LIMIT: ${{secrets.GH_API_CONCURRENCY_LIMIT}}
          GH_API_USERNAME: ${{secrets.GH_API_USERNAME}}
          GH_API_TOKEN: ${{secrets.GH_API_TOKEN}}
      - run: yarn run build:site
        env:
          HOSTED_AT: ${{secrets.HOSTED_AT}}
      - run: git config --global user.name "Tooling Builder"
      - run: git config --global user.email "tooling@openapis.org"
      - run: |
          git add docs/categories
          git commit -a -m "chore: Metadata build (updates to OpenAPI tooling metadata and site rebuild)"
          git push origin main
          on:
  push:
    branches:
    - main
    - release/*
    on:
  pull_request:
    branches:
    - main
    on:
  schedule:
  - cron: "0 2 * * 1-5"
  on:
  pull_request:
    branches:
    - main
    jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    - name: Setup Node
  uses: actions/setup-node@v1
  with:
    node-version: '10.x'
    - name: Install Dependencies
  run: npm install
  jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
        steps:
- run: npm publish
  if: github.event_name == 'push'
